title: My Resume
url: 'https://yirendataanalysis.github.io/'
baseurl: '' #change it according to your repository name

# Profile information
yourname: Yi Ren  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Houston, TX

github: [metadata]

## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com/in/YiRenDataAnalysis    ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url
github: https://github.com/yirendataanalysis/

# Update all the sections by editing the files inside _includes folder.
