title: My Resume
url: 'https://yirendataanalysis.github.io/'
baseurl: '' #change it according to your repository name

# Profile information
yourname: Yi Ren  ## put your name
title: 'RESEARCHER &amp; DATA SCIENTIST'  ## your title
location: Houston, TX
email: yiren.chn@gmail.com
phone: 713-820-8964
resume: "/assets/Yi-Ren-Resume.pdf"
about : "Research Manager and statistician with and extensive background in research methods, program evaluation, statistical concepts and programming. Produced over 20 publications using data and research skills. "
image: "/assets/images/img/front.jpg"

github: [metadata]

## Social Profiles
social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "http://www.linkedin.com/in/YiRenDataAnalysis"
    - icon: fa-github
      link: "https://github.com/yirendataanalysis"
    # - icon: fa-dribbble
    #   link: "#"
    # - icon: fa-foursquare
    #   link: "#"
